In [1]:
import numpy as np
data = np.array([
    [101, 25],
    [102, 30],
    [103, 28],
    [104, 35]
])

selected = data[[0, 2]]
print(selected)


[[101  25]
 [103  28]]


In [3]:
import numpy as np
image = np.zeros((3,3))
image[2, 2] = 255

print(image)


[[  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0. 255.]]
