**1D**

In [2]:
import numpy as np



In [3]:
arr1=np.array([10,20,30,40])

In [4]:
arr1.shape

(4,)

In [5]:
arr1.size

4

In [6]:
arr1.ndim

1

**2D**

In [7]:
l1=[10,20,30,40]
l2=[1,2,3,4]

In [8]:
arr2=np.array([[[[l1,l2]]]])

In [9]:
arr2

array([[[[[10, 20, 30, 40],
          [ 1,  2,  3,  4]]]]])

In [10]:
arr2.size

8

In [11]:
arr2.shape

(1, 1, 1, 2, 4)

In [12]:
arr2.ndim

5

In [13]:
l1=[10,20,30]
l=[l1]
arr1=np.array(l)
print(arr1)
print('shape : ',arr1.shape)
print('dim : ',arr1.ndim)

# there are 1 list 
# there has 3 element

[[10 20 30]]
shape :  (1, 3)
dim :  2


In [14]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l3=[100,200,300,400]
l4=[l1,l2,l3]
arr2=np.array(l4)
print(arr2)
print('shape : ',arr2.shape)
print('dim : ',arr2.ndim)

# there are 3 list 
# there has 4 element

[[ 10  20  30  40]
 [  1   2   3   4]
 [100 200 300 400]]
shape :  (3, 4)
dim :  2


In [15]:
l1=[10,20,30]
l2=[1,2,3]
l3=[100,200,300]
l4=[l1,l2,l3]
arr3=np.array(l4)
print(arr2)
print('shape : ',arr3.shape)
print('dim : ',arr3.ndim)

# there are 3 list 
# there has 3 element

[[ 10  20  30  40]
 [  1   2   3   4]
 [100 200 300 400]]
shape :  (3, 3)
dim :  2


***3D***

In [16]:
l1=[10,20,30]
l2=[1,2,3]
l3=[100,200,300]
l4=[[l1,l2,l3]]
arr3=np.array(l4)
print(arr3)
print('shape : ',arr3.shape)
print('dim : ',arr3.ndim)
len(arr3)
# there are 3 list 
# there has 3 element

[[[ 10  20  30]
  [  1   2   3]
  [100 200 300]]]
shape :  (1, 3, 3)
dim :  3


1

In [17]:
# 3,2,3
l1=[10,20,30]      #k=3
l2=[l1,l1]         #n=2
l3=[l2,l2,l2]      #m=3
np.array(l3)       #m,n,k

array([[[10, 20, 30],
        [10, 20, 30]],

       [[10, 20, 30],
        [10, 20, 30]],

       [[10, 20, 30],
        [10, 20, 30]]])

In [18]:
# 4,2,2,4
l1=[10,20,30,40]      #k=3
l2=[l1,l1]            #n=2
l3=[l2,l2]            #m=3
l4=[l3,l3,l3,l3]             
np.array(l4).shape    #m,n,k

(4, 2, 2, 4)

In [19]:
# 4,2,2,4
l1=[10]
l2=[l1,l1]#k=3
l3=[l2,l2,l2]            #n=2
l4=[l3,l3,l3,l3]            #m=3
l5=[l4,l4,l4,l4,l4]             
np.array(l5)    #m,n,k

array([[[[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]]],



       [[[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]]],



       [[[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          

In [20]:
# 4,2,2,4
l1=[10]
l2=[l1,l1]#k=3
l3=[l2,l2,l2]            #n=2
l4=[l3,l3,l3,l3]            #m=3
l5=[l4,l4,l4,l4,l4]             
np.array(l5)

array([[[[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]]],



       [[[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]]],



       [[[[10],
          [10]],

         [[10],
          [10]],

         [[10],
          [10]]],


        [[[10],
          [10]],

         [[10],
          

In [22]:
l1=[10]
l2=[['hiiiii','hiiiii'],['hiiii','hiiiiii'],l1]#k=3
l3=[['Rohit','Rohit'],['Rohit','Rohit'],['Rohit','Rohit'],l2]            #n=2
l4=[['12','12'],['12','12'],['12','12'],['12','12'],l3]            #m=3
l5=[['45','45'],['65','45'],['213','4584'],['78','454'],[['213','4584']],l4] 
np.array(l5)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

In [28]:
import numpy as np

arr = np.full((5, 4, 3, 2, 1), 'Rohit')


In [29]:
print(arr)
print(arr.shape)
print(arr.dtype)


[[[[['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]]


  [[['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]]


  [[['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]]


  [[['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]]]



 [[[['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]]


  [[['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]]


  [[['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]]


  [[['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]]]



 [[[['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]]


  [[['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]]


  [[['Rohit']
    ['Rohit']]

   [['Rohit']
    ['Rohit']]

   [['Rohit']
  