In [ ]:
# Numpy means 
=> Numerical python or number python is used for math operations
=> generaly elements provided in following format or types
=>
    -Lists
    -tuples
    -array
                                             
=> Lists and tuples are basic level representations with no shape and dimensions                                             
=> Math operations are slow with list and tuples
=> Numpy array are having shapes and dimensions 
=> Numpy arrays and tensors are both same in nature
=> When cpu is there numpy array are enough to perform the operations
=> when gpu is there then Tensors are required to perform the operation

In [70]:
import numpy as np

In [71]:
np.__version__

'2.4.1'

In [72]:
pip show numpy

Name: numpy
Version: 2.4.1
Summary: Fundamental package for array computing in Python
Home-page: 
Author: Travis E. Oliphant et al.
Author-email: 
License: 
Location: D:\Data-Science\venv\Lib\site-packages
Requires: 
Required-by: contourpy, matplotlib, pandas, scikit-learn, scipy, seaborn
Note: you may need to restart the kernel to use updated packages.


In [73]:
import sys

In [74]:
sys.version


'3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]'

In [75]:
l=[1,2,3,4]

In [76]:
arr1=np.array(l)

In [77]:
type(arr1)
#Ndimensional arrray

numpy.ndarray

**Why NumPy is famous**


In [78]:
l1=[10,20,30]
l2=[100,200,300]
l3=[]
# for i in range(len(l1)):
#     l3.append(l1[i]+l2[i])
for i,j in zip(l1,l2):
    l3.append(i+j)
print(l3)

[110, 220, 330]


In [79]:
l2=[100,200,300]
l1=[10,20,30]
arr1=np.array(l1)
arr2=np.array(l2)
arr1+arr2

array([110, 220, 330])

In [80]:
# l1*l2   Not possible
arr1*arr2

array([1000, 4000, 9000])

In [81]:
# l1/l2 Not [ossible
arr1/arr2

array([0.1, 0.1, 0.1])

In [82]:
l2=[100,200,300]
arr1=np.array(l2)

In [83]:
list(arr1)

[np.int64(100), np.int64(200), np.int64(300)]

In [84]:
arr1.tolist()

[100, 200, 300]

In [85]:
import time
start=time.time()
l1=list(range(1,10000000))
l2=list(range(1,10000000))
l3=[i*j for i,j in zip(l1,l2)]
end=time.time()
print(end-start)

1.7900145053863525


In [86]:
import time
start=time.time()
arr1=np.array(l1)
arr2=np.array(l2)
arr3=arr1*arr2
end=time.time()
print(end-start)

1.752018690109253
