In [13]:
import pickle
import numpy as np

In [14]:
ohe_sex=pickle.load(open('D:\Data-Science\ML\CampusX\Pipeline\ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open('D:\Data-Science\ML\CampusX\Pipeline\ohe_embarked.pkl','rb'))
clf=pickle.load(open('D:\Data-Science\ML\CampusX\Pipeline\clf.pkl','rb'))

In [15]:
# Assume User Input
# Pclass/gender/age/sibsp//parch/fare/embarked
test_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [16]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [18]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))

D:\Data-Science\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [19]:
X_test_rem = X_test.drop(columns=['Sex','Age','Embarked' ])


array([[0., 1.]])

In [24]:
Test_input_embarked = ohe_embarked. transform(test_input[:, -1].reshape(1,1))
Test_input_embarked

D:\Data-Science\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0.]])

In [26]:
test_input_age=test_input[:,2].reshape(1,1)