In [26]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn. impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn. preprocessing import MinMaxScaler
from sklearn. tree import DecisionTreeClassifier

In [27]:
df=sns.load_dataset('titanic')

In [28]:
df.drop(columns=['class','who','adult_male','deck','embark_town','alive','alone'],inplace=True)

In [29]:
# Step 1
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['survived']),df['survived'],test_size=0.2,random_state=42)

In [30]:
X_train.head(2)

,pclass,sex,age,sibsp,parch,fare,embarked
331,1,male,45.5,0,0,28.5,S
733,2,male,23.0,0,0,13.0,S


In [31]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: survived, dtype: int64

In [32]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

In [33]:
# Applying Stratigic
si_age=SimpleImputer(strategy='mean')
si_embarked=SimpleImputer(strategy='most_frequent')
X_train_age=si_age.fit_transform(X_train[['age']])
X_test_age=si_age.fit_transform(X_test[['age']])
X_train_embarked=si_embarked.fit_transform(X_train[['embarked']])
X_test_embarked=si_embarked.fit_transform(X_test[['embarked']])

In [34]:
X_train_age

array([[45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [29.49884615],
       [29.        ],
       [36.        ],
       [29.49884615],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [29.49884615],
       [29.49884615],
       [24.        ],
       [18.        ],
       [29.49884615],
       [25

In [35]:
# Applying one hot encoding on sex and embarked
ohe_sex=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
X_train_sex=ohe_sex.fit_transform(X_train[['sex']])
X_train_embarked=ohe_embarked.fit_transform(X_train_embarked)
X_test_embarked=ohe_embarked.fit_transform(X_test_embarked)
X_test_sex=ohe_embarked.fit_transform(X_test[['sex']])

In [36]:
X_train_sex

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]], shape=(712, 2))

In [37]:
X_train_rem=X_train.drop(columns=['sex','age','embarked'])

In [38]:
X_test_rem=X_test.drop(columns=['sex','age','embarked'])

In [39]:
X_train_transformed=np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)

In [40]:
X_test_transformed=np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)

In [41]:
clf=DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)
y_pred=clf.predict(X_test_transformed)

In [42]:
y_pred

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0])

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7430167597765364

In [44]:
import pickle

In [45]:
pickle.dump(ohe_sex,open('D:\Data-Science\ML\CampusX\Pipeline\ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('D:\Data-Science\ML\CampusX\Pipeline\ohe_embarked.pkl','wb'))
pickle.dump(clf,open('D:\Data-Science\ML\CampusX\Pipeline\clf.pkl','wb'))