In [5]:
import numpy as np
numpy_array=np.zeros((3,3))
print(numpy_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
import numpy as np
arr=np.zeros((2,3), dtype=float)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
import numpy as no
arr=np.ones((2,3), dtype=str)
print(arr)

[['1' '1' '1']
 ['1' '1' '1']]


In [20]:
import numpy as np
arr=np.empty((2,2))
print(arr)

[[0.00000000e+000 9.56845419e-312]
 [9.56845418e-312 9.56845417e-312]]


In [25]:
import numpy as np
arr=np.arange(0,10,2)
print(arr)
arr1=np.arange(10,-10,-2)
print(arr1)

[0 2 4 6 8]
[10  8  6  4  2  0 -2 -4 -6 -8]


In [35]:
import numpy as np
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [38]:
import numpy as np
arr=np.full((2,3),2)
print(arr)

[[2 2 2]
 [2 2 2]]


In [41]:
import numpy as np
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
