## np.full() — what it is, how it works, and why it’s used
## What np.full() does

Creates a NumPy array of a given shape, where every element has the same value you choose.

## Basic syntax

np.full(shape, fill_value, dtype=None)


shape → tuple like (rows, cols)

fill_value → the constant value to repeat

dtype → optional data type

## Example with output

import numpy as np

a = np.full((2, 3), 7)

print(a)

Output
[[7 7 7]
 [7 7 7]]

## Why np.full() is used (real reasons)

1. Custom initialization

When 0 or 1 is not meaningful

Example: initializing with -1, NaN, or a sentinel value

np.full((3, 3), -1)


2. Missing / placeholder values

Common in data preprocessing

Marks “unknown” or “unfilled” entries clearly

np.full((4,), np.nan)


3. Testing and debugging

Easier to spot errors when all values are identical

## Reality check / limitations (don’t ignore)

❌ Uses full memory immediately (same as zeros)

❌ Can hide logic errors if you forget to replace values

❌ Not efficient if array will be immediately overwritten

⚠️ Default dtype depends on fill_value

np.full((2,2), 3)      # int
np.full((2,2), 3.0)    # float

## When you should not use np.full()

If you need performance and will overwrite everything → use np.empty()

If 0 or 1 already makes sense → use zeros() / ones()

In [4]:
import numpy as np
ful=np.full((2,3),5)
print(ful)

[[5 5 5]
 [5 5 5]]
