# Identity Matrix — what it is, why it exists, and how it’s used
# What is an identity matrix?

An identity matrix is a square matrix where:

All diagonal elements are 1

All other elements are 0

It’s the matrix equivalent of the number 1 in multiplication.

# Example (3 × 3 identity matrix)
import numpy as np

I = np.eye(3)

print(I)

# Output
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

# Why identity matrices are used (real reasons)
# 1️⃣ Neutral element in matrix multiplication

Multiplying any matrix by an identity matrix does not change it.

A = np.array([[2, 3],
              [4, 5]])

I = np.eye(2)

print(A @ I)

# Output
[[2 3]
 [4 5]]


# Why this matters

Used to verify matrix operations

Acts like × 1 in algebra

# 2️⃣ Matrix inverse definition

A matrix inverse exists only if:

A × A⁻¹ = I


Without identity matrices:

Inverses have no formal meaning

Linear systems cannot be solved cleanly

# 3️⃣ Solving linear equations

Used in:

Linear regression (normal equation)

Systems of equations

Optimization problems

Example concept:

Ax = b  →  x = A⁻¹b

# 4️⃣ Machine Learning & Data Science

Identity matrices are used for:

Regularization (adding stability)

Covariance matrices

Initialization in algorithms

# Example:

np.eye(n) * lambda_value

# How to create identity matrices in NumPy
#Using np.eye()

np.eye(4)

Using np.identity()

np.identity(4)


# ⚠️ Difference (important):

np.identity() only works for square matrices

np.eye() allows offset diagonals

# Offset diagonal example (advanced but useful)
np.eye(3, k=1)


# Output:

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

# Limitations / reality check

❌ Only defined for square matrices

❌ Useless alone — meaningful only in operations

❌ Large identity matrices waste memory if used blindly

⚠️ Often confused with diagonal matrices (not the same)

In [1]:
import numpy as np
iden=np.eye(3)
print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np
iden=np.eye(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
import numpy as np
iden=np.eye(5)
print(iden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
import numpy as np
iden=np.eye(10)
print(iden)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
