In [2]:
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
import numpy as np
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
import numpy as np
arr=np.empty((3,3))
print(arr)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.06811083e-306 1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 0.00000000e+000]]


In [15]:
import numpy as np
arr=np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [24]:
import numpy as np
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [22]:
import numpy as np
arr=np.full((2,3),7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [28]:
import numpy as np
a=np.array([1,2,3])
b=a.astype(float)
print(a)
print(b)
print(a.dtype,b.dtype)

[1 2 3]
[1. 2. 3.]
int64 float64


In [29]:
import numpy as np
arr=np.array([1,2,3,4,6])
print(arr+5)

[ 6  7  8  9 11]


In [42]:
import numpy as np
a=np.array([ 6 , 7,  8,  9, 11])
sum1=np.sum(a)
men=np.mean(a)
mi=np.min(a)
ma=np.max(a)
min1=np.argmin(a)
max1=np.argmax(a)
print(max1)
print(min1)
print(ma)
print(mi)
print(men)
print(sum1)

4
0
11
6
8.2
41


In [47]:
import numpy as np
a=np.array([[1,2,3,4],
           [5,6,7,8]])
su=np.sum(a, axis=1)
print(su)

[10 26]
